# Generated by Django 5.2.10 on 2026-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_delete_dataset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadhistory',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Upload History', 'verbose_name_plural': 'Upload History'},
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='dataset_name',
            field=models.CharField(help_text='Name of the uploaded CSV file', max_length=150),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='total_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='type_distribution',
            field=models.JSONField(help_text='Equipment type counts'),
        ),
    ]
